### ISSUE TITLE
Export a file that maps bibstem to most-recent publisher

### ISSUE THREAD

**Issue by seasidesparrow** [adsabs/ADSJournalsDB#59]
ADSCachedExports needs to have access to a publisher-bibstem map.  There are multiple ways to achieve this:
- API call to the summary endpoint with the bibstem
- Redis cache with the mapping
- Flat file to provision ADSCachedExports with

Of these three, the flat file option is probably most consistent with the existing infrastructure: the redis cache would involve additional infrastructure and provisioning of the import_pipeline container that isn't straightforward; the API call would currently require either calling the API once for every record, or calling the API and querying all known bibstems for their publisher, and caching the result in a dict.

**NOTE: anything that we do requires that we have a complete mapping of bibstem to publisher in journals database itself, and this is currently an ongoing curation project.  That curation work must be completed before we rely on the journals database as the origin of this mapping.**  

The proposed location for this would be in the task `task_export_classic_files`.  We would need to add code to utils to create formatted output, and add a variable to config containing the path/name of the destination file.

**Comment by ehenneken** [comment]
I agree that the flat file option is the most consistent with the existing infrastructure. We wouldn't want the Import Pipeline (via ADSCachedExports) be dependent on calls to an external service.

**Comment by seasidesparrow** [comment]
@ehenneken The other classic files I'm exporting have a row/size count at the top.  Do you want the first line of this file to be a row count, or just the data, no header?

**Comment by ehenneken** [comment]
@seasidesparrow Let's put the row count on the first line, please.

**Comment by seasidesparrow** [comment]
Implemented in #60
